const URDU_BASE='https://hebron10.github.io/urdu-bible-json';
const ENGLISH_API='https://api.midvash.com/v1';
const KEY='bqj-v2';
const CATEGORIES=['Critical / Objection','Theological','Moral / Ethical','Historical','Cultural','Scientific / Natural','Translation / Language','Contradiction / Tension','Chronology / Timeline','Genealogy','Prophecy','Symbolism','Interpretation','Cross-reference','Personal / Application','Other'];
const STATUSES=['Unanswered','Investigating','Partially answered','Answered','Need further investigation'];
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{};
const SUPABASE_URL='https://korlocuvqddcbnzekzny.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_xqYdeaDBUxmxI7DJikN4Aw_8gc21Qxx';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let cloudUser=null,cloudReady=false,cloudLoading=false,cloudSyncTimer=null,appStarted=false;
const books=[
['Pydāish','PYD','GEN',50],['Khurooj','KHU','EXO',40],['Ahbaar','AHB','LEV',27],['Ginti','GIN','NUM',36],['Istisna','IST','DEU',34],['Yashua','YSH','JOS',24],['Qazaat','QAZ','JDG',21],['Rut','RUT','RUT',4],['1 Samuel','1SM','1SA',31],['2 Samuel','2SM','2SA',24],['1 Salateen','1SL','1KI',22],['2 Salateen','2SL','2KI',25],['1 Tawareekh','1TA','1CH',29],['2 Tawareekh','2TA','2CH',36],['Uzair','UZR','EZR',10],['Nehemiah','NEM','NEH',13],['Esther','EST','EST',10],['Ayyub','AYY','JOB',42],['Zaboor','ZBR','PSA',150],['Amsaal','AMS','PRO',31],['Jamaat','JAM','ECC',12],['Ghazal-e-Ghazal','GHA','SNG',8],['Yasaiah','YSA','ISA',66],['Yeremiah','YRM','JER',52],['Nohah','NOM','LAM',5],['Hizqiyal','HZQ','EZK',48],['Daniyal','DAN','DAN',12],['Hosea','HOS','HOS',14],['Yoel','YOE','JOL',3],['Aamoos','AAM','AMO',9],['Obadiah','ABD','OBA',1],['Yonas','YUN','JON',4],['Mikaah','MIK','MIC',7],['Nahum','NAH','NAM',3],['Habakkuk','HAB','HAB',3],['Safanya','SFM','ZEP',3],['Haggai','HAG','HAG',2],['Zakariya','ZKR','ZEC',14],['Malaaki','MLK','MAL',4],['Matta','MAT','MAT',28],['Marqus','MRQ','MRK',16],['Luqa','LUQ','LUK',24],['Yuhanna','YUH','JHN',21],['Rasoolon ke Amaal','RAA','ACT',28],['Romiyon','ROM','ROM',16],['1 Korinthiyon','1KR','1CO',16],['2 Korinthiyon','2KR','2CO',13],['Galatiyon','GAL','GAL',6],['Efesiyon','EFE','EPH',6],['Philippiyon','PHL','PHP',4],['Kuliwsiyon','KUL','COL',4],['1 Thessaluniki','1TH','1TH',5],['2 Thessaluniki','2TH','2TH',3],['1 Timothi','1TM','1TI',6],['2 Timothi','2TM','2TI',4],['Titus','TIT','TIT',3],['Philemon','PHM','PHM',1],['Ibraniyon','IBR','HEB',13],['Yaqoob','YAQ','JAS',5],['1 Patras','1PT','1PE',5],['2 Patras','2PT','2PE',3],['1 Yuhanna','1YU','1JN',5],['2 Yuhanna','2YU','2JN',1],['3 Yuhanna','3YU','3JN',1],['Yahoodah','YHD','JUD',1],['Mukashafa','MUK','REV',22]
].map(([name,code,apiId,chapters],index)=>({name,code,apiId,chapters,index}));
const byName=Object.fromEntries(books.map(b=>[b.name,b]));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto?.randomUUID?.()||`q_${Date.now()}_${Math.random().toString(36).slice(2)}`;
function save(){
  localStorage.setItem(KEY,JSON.stringify(state));
  if(cloudUser&&cloudReady&&!cloudLoading){
    clearTimeout(cloudSyncTimer);
    cloudSyncTimer=setTimeout(()=>syncStateToCloud().catch(err=>console.warn('Cloud sync failed',err)),250);
  }
}
const toast=msg=>{const x=document.getElementById('toast');x.textContent=msg;x.className='show';clearTimeout(window._t);window._t=setTimeout(()=>x.className='',2400)};
function bookByCode(code){return books.find(b=>b.code===code)||books[0]}
function currentBook(){return byName[state.reading.book]||books[0]}
function normalizePoint(p,fallback){const b=byName[p?.book]||fallback||currentBook();const ch=Math.max(1,Math.min(Number(p?.chapter)||1,b.chapters));const verse=Math.max(1,Number(p?.verse)||1);return {book:b.name,chapter:ch,verse}}
function normalizeRange(r,fallback){const from=normalizePoint(r?.from||r,fallback);const to=r?.to?normalizePoint(r.to,byName[r.to.book]||fallback):null;return {from,to:to&&((to.book!==from.book)||(to.chapter!==from.chapter)||(to.verse!==from.verse))?to:null}}
function parseLegacyReference(ref,book){
  const raw=String(ref||'').trim(); if(!raw)return null;
  const clean=raw.replace(/[–—]/g,'-').replace(/\s+/g,' ');
  const pieces=clean.split(/\s*-\s*/);
  const parsePoint=(text,base)=>{
    const s=String(text||'').trim();
    let m=s.match(/^(?:(.+?)\s+)?(\d+)\s*:\s*(\d+)$/);
    if(m){const b=byName[m[1]?.trim()]||base||book;return {book:b.name,chapter:Number(m[2]),verse:Number(m[3])};}
    m=s.match(/^(?:(.+?)\s+)?(\d+)$/);
    if(m){const b=byName[m[1]?.trim()]||base||book;return {book:b.name,chapter:Number(m[2]),verse:base?.verse||1};}
    return null;
  };
  const from=parsePoint(pieces[0],book);
  if(!from)return null;
  if(pieces.length===1)return normalizeRange({from,to:null},book);
  const endpoint=pieces.slice(1).join('-').trim();
  let to=parsePoint(endpoint,byName[from.book]||book);
  if(/^\d+$/.test(endpoint))to={book:from.book,chapter:from.chapter,verse:Number(endpoint)};
  if(/^\d+\s*:\s*\d+$/.test(endpoint))to={book:from.book,chapter:Number(endpoint.split(':')[0]),verse:Number(endpoint.split(':')[1])};
  return normalizeRange({from,to},book);
}
function formatRange(r){if(!r?.from)return '—';const a=r.from,b=r.to;if(!b)return `${a.chapter}:${a.verse}`;if(a.book===b.book&&a.chapter===b.chapter)return `${a.chapter}:${a.verse}–${b.verse}`;if(a.book===b.book)return `${a.chapter}:${a.verse}–${b.chapter}:${b.verse}`;return `${a.book} ${a.chapter}:${a.verse}–${b.book} ${b.chapter}:${b.verse}`}
function setAuthMessage(message=''){const el=document.getElementById('authMessage');if(el)el.textContent=message}
function setAuthVisible(visible){const gate=document.getElementById('authGate');if(gate)gate.hidden=!visible}
function setAccountUI(user){const email=user?.email||'';const el=document.getElementById('accountEmail');if(el)el.textContent=email;}
function isUuid(value){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value||''))}
function questionRow(q,index){return {id:isUuid(q.uid)?q.uid:uid(),user_id:cloudUser.id,question_id:q.id,book:q.book,book_code:q.code,chapter:String(q.chapter??q.primaryReference?.from?.chapter??1),verse:formatRange(q.primaryReference),additional_reference:(q.additionalReferences||[]).map(formatRange).join('; '),question:q.question,why_asked:q.why||'',category:q.category,related_questions:q.related||[],status:q.status,investigation_answer:q.investigation||'',sources:q.sources||'',conclusion:q.conclusion||'',sort_order:index,date_added:(q.createdAt||new Date().toISOString()).slice(0,10),created_at:q.createdAt||new Date().toISOString(),updated_at:new Date().toISOString()}}
function readingRows(){const last=state.reading.last||{book:'Pydāish',chapter:1,verse:1};return books.map(b=>{const p=readingPosition(b);const completed=[];for(let c=1;c<=b.chapters;c++)if(isCompleted(b.name,c))completed.push(c);return {user_id:cloudUser.id,book:b.name,book_code:b.code,current_chapter:p.chapter,current_verse:p.verse,completed:false,updated_at:new Date().toISOString(),completed_chapters:completed,is_last:b.name===last.book}})}
async function syncStateToCloud(){
  if(!cloudUser||cloudLoading)return;
  const rows=state.questions.map((q,i)=>questionRow(q,i));
  if(rows.length){
    const {error}=await supabaseClient.from('questions').upsert(rows,{onConflict:'id'});if(error)throw error;
    const researchRows=state.questions.map(q=>({question_id:isUuid(q.uid)?q.uid:null,user_id:cloudUser.id,status:q.status,research_notes:q.investigation||'',sources:q.sources||'',conclusion:q.conclusion||'',search_query:buildResearchQuery(q),floating_x:q.researchUi?.x??null,floating_y:q.researchUi?.y??null,updated_at:new Date().toISOString()})).filter(r=>r.question_id);
    if(researchRows.length){const {error:e2}=await supabaseClient.from('research').upsert(researchRows,{onConflict:'question_id'});if(e2)throw e2}
  }
  const {error:e3}=await supabaseClient.from('reading_progress').upsert(readingRows(),{onConflict:'user_id,book_code'});if(e3)throw e3;
}
function applyCloudQuestions(rows,researchRows){
  const researchMap=new Map((researchRows||[]).map(r=>[r.question_id,r]));
  state.questions=(rows||[]).sort((a,b)=>a.sort_order-b.sort_order).map(r=>{const rr=researchMap.get(r.id);const b=byName[r.book]||bookByCode(r.book_code);const parsed=parseLegacyReference(r.verse,b)||{from:{book:b.name,chapter:Number(r.chapter)||1,verse:1},to:null};const additional=String(r.additional_reference||'').split(';').map(x=>parseLegacyReference(x,b)).filter(Boolean);return {uid:r.id,id:r.question_id,code:b.code,book:b.name,chapter:parsed.from.chapter,primaryReference:parsed,additionalReferences:additional,references:[formatRange(parsed),...additional.map(formatRange)],question:r.question||'',why:r.why_asked||'',category:CATEGORIES.includes(r.category)?r.category:'Other',status:STATUSES.includes(r.status)?r.status:'Unanswered',related:Array.isArray(r.related_questions)?r.related_questions:[],investigation:rr?.research_notes||r.investigation_answer||'',sources:rr?.sources||r.sources||'',conclusion:rr?.conclusion||r.conclusion||'',createdAt:r.created_at||new Date().toISOString(),researchUi:{x:rr?.floating_x??null,y:rr?.floating_y??null,minimized:false}}});
}
async function loadCloudState(){
  cloudLoading=true;
  const [{data:questions,error:qErr},{data:research,error:rErr},{data:progress,error:pErr}]=await Promise.all([
    supabaseClient.from('questions').select('*').eq('user_id',cloudUser.id).order('sort_order',{ascending:true}),
    supabaseClient.from('research').select('*').eq('user_id',cloudUser.id),
    supabaseClient.from('reading_progress').select('*').eq('user_id',cloudUser.id)
  ]);
  if(qErr||rErr||pErr)throw qErr||rErr||pErr;
  const hasCloud=Boolean((questions||[]).length||(progress||[]).length);
  if(hasCloud){
    applyCloudQuestions(questions||[],research||[]);
    state.reading.completed={};state.reading.positions={};
    (progress||[]).forEach(r=>{const b=byName[r.book]||bookByCode(r.book_code);state.reading.positions[b.name]={chapter:Number(r.current_chapter)||1,verse:Number(r.current_verse)||1};(r.completed_chapters||[]).forEach(c=>state.reading.completed[b.name+'|'+c]=true)});
    const lastRow=(progress||[]).find(r=>r.is_last)||((progress||[]).slice().sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0]);const last=lastRow?{book:(byName[lastRow.book]||bookByCode(lastRow.book_code)).name,chapter:Number(lastRow.current_chapter)||1,verse:Number(lastRow.current_verse)||1}:{book:'Pydāish',chapter:1,verse:1};state.reading.last=last;state.reading.book=last.book;state.reading.chapter=last.chapter;state.reading.verse=last.verse;
  }else{
    if(state.questions.length)await syncStateToCloud();
    else await syncStateToCloud();
  }
  cloudLoading=false;cloudReady=true;save();
}
async function cloudDeleteQuestion(uidToDelete){if(!cloudUser||!isUuid(uidToDelete))return;const {error}=await supabaseClient.from('questions').delete().eq('id',uidToDelete).eq('user_id',cloudUser.id);if(error)console.warn('Cloud delete failed',error)}
async function startAuthenticatedApp(session){
  if(appStarted)return;
  cloudUser=session.user;setAccountUI(cloudUser);setAuthMessage('');
  try{await loadCloudState();}catch(err){console.error(err);cloudLoading=false;cloudReady=false;setAuthMessage('Could not load your cloud journal. Check your connection and try again.');setAuthVisible(true);return}
  initialize();appStarted=true;setAuthVisible(false);
}
async function bootAuth(){
  document.getElementById('googleSignIn').onclick=async()=>{setAuthMessage('Opening Google…');const {error}=await supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.href}});if(error)setAuthMessage(error.message)};
  document.getElementById('signOutButton').onclick=async()=>{await supabaseClient.auth.signOut();window.location.reload()};
  supabaseClient.auth.onAuthStateChange((event,session)=>{if(session)setTimeout(()=>startAuthenticatedApp(session),0);else{cloudUser=null;cloudReady=false;setAuthVisible(true);}});
  const {data,error}=await supabaseClient.auth.getSession();
  if(error){setAuthMessage(error.message);setAuthVisible(true);return}
  if(data.session)await startAuthenticatedApp(data.session);else setAuthVisible(true);
}
function migrate(){
  state.reading=state.reading||{book:'Pydāish',chapter:1,verse:1,completed:{}};
  state.reading.completed=state.reading.completed||{};
  state.reading.positions=state.reading.positions||{};
  if(!state.reading.positions[state.reading.book])state.reading.positions[state.reading.book]={chapter:Number(state.reading.chapter)||1,verse:Number(state.reading.verse)||1};
  state.reading.last=state.reading.last||{book:state.reading.book,chapter:Number(state.reading.chapter)||1,verse:Number(state.reading.verse)||1};
  state.questions=Array.isArray(state.questions)?state.questions:[];
  state.questions.forEach(q=>{
    q.uid=q.uid||uid(); q.code=q.code||bookByCode(q.code).code; q.book=byName[q.book]?.name||bookByCode(q.code).name;
    q.category=CATEGORIES.includes(q.category)?q.category:'Other'; q.status=STATUSES.includes(q.status)?q.status:'Unanswered';
    if(!q.primaryReference){
      const first=(q.references||[])[0]; q.primaryReference=parseLegacyReference(first,q.book?byName[q.book]:currentBook())||{from:{book:q.book||'Pydāish',chapter:Number(q.chapter)||1,verse:1},to:null};
    }else q.primaryReference=normalizeRange(q.primaryReference,byName[q.book]||currentBook());
    q.additionalReferences=Array.isArray(q.additionalReferences)?q.additionalReferences.map(x=>normalizeRange(x,byName[q.book]||currentBook())).filter(Boolean):[];
    if(!q.additionalReferences.length && Array.isArray(q.references)&&q.references.length>1)q.additionalReferences=q.references.slice(1).map(x=>parseLegacyReference(x,byName[q.book]||currentBook())).filter(Boolean);
    q.references=[formatRange(q.primaryReference),...(q.additionalReferences||[]).map(formatRange)];
    q.related=Array.isArray(q.related)?q.related:[]; q.investigation=q.investigation||'';q.sources=q.sources||'';q.conclusion=q.conclusion||'';
    q.researchUi=q.researchUi||{x:null,y:null,minimized:false};
  });
  if(!state.research)state.research={};
  if(!state.selectedLanguage)state.selectedLanguage='ur';
  if(!state.translations)state.translations=[]; if(!state.cache)state.cache={};
  save();
}
migrate();
function isCompleted(book,ch){return !!state.reading.completed[book+'|'+ch]}
function completedCount(book){let n=0;for(let c=1;c<=book.chapters;c++)if(isCompleted(book.name,c))n++;return n}
function completedBooks(){return books.filter(b=>completedCount(b)===b.chapters).length}
function bookProgress(book){const done=completedCount(book),pos=state.reading.positions[book.name];return {done,pos,percent:done===book.chapters?100:Math.round(done/book.chapters*100)}}
function nextId(book){const n=state.questions.filter(q=>q.code===book.code).length+1;return `${book.code} ${String(n).padStart(3,'0')}`}
function renumberBook(code){const qs=state.questions.filter(q=>q.code===code);const map=new Map();qs.forEach((q,i)=>{const old=q.id;const next=`${code} ${String(i+1).padStart(3,'0')}`;map.set(old,next);q.id=next});state.questions.forEach(q=>{q.related=(q.related||[]).map(r=>map.get(r)||r)});save()}
function populateBookSelect(id,selected){const s=document.getElementById(id);if(!s)return;s.innerHTML=books.map(b=>`<option value="${esc(b.name)}">${esc(b.name)}</option>`).join('');if(selected&&byName[selected])s.value=selected}
function populateChapterSelect(id,bookName,selected=1){const s=document.getElementById(id);if(!s)return;const b=byName[bookName]||books[0];s.innerHTML=Array.from({length:b.chapters},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');s.value=String(Math.min(Math.max(1,Number(selected)||1),b.chapters))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.getElementById('title').textContent={dashboard:'Dashboard',bible:'Bible',questions:'Questions',add:'Add Question',research:'Research & Review'}[id]||id;const bubble=document.getElementById('researchBubble');if(bubble&&id!=='research')bubble.hidden=true;if(id==='dashboard')renderDashboard();if(id==='questions')renderQuestions();if(id==='research'){renderResearch();const q=state.questions.find(x=>x.uid===window.selectedQuestionUid);if(bubble)bubble.hidden=!q?.researchUi?.minimized}}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>show(x.dataset.page));
function setSide(){const b=currentBook(),p=state.reading.positions[b.name]||{chapter:1,verse:1};document.getElementById('sideBook').textContent=b.name;document.getElementById('sideChapter').textContent=`Chapter ${p.chapter} · ${isCompleted(b.name,p.chapter)?'Completed':'In progress'}`}
function readingPosition(book){return state.reading.positions[book.name]||{chapter:1,verse:1}}
function setReadingPosition(book,chapter,verse=1){const b=book||currentBook();const p={chapter:Math.max(1,Math.min(Number(chapter)||1,b.chapters)),verse:Math.max(1,Number(verse)||1)};state.reading.positions[b.name]=p;state.reading.book=b.name;state.reading.chapter=p.chapter;state.reading.verse=p.verse;state.reading.last={book:b.name,...p};save();setSide()}
function updateBookProgressUI(){const b=currentBook(),p=readingPosition(b),done=completedCount(b);document.getElementById('bookProgressTitle').textContent=b.name;document.getElementById('bookProgressNumber').textContent=`${p.chapter} / ${b.chapters}`;document.getElementById('bookProgressBar').style.width=(p.chapter/b.chapters*100)+'%';document.getElementById('dashReading').textContent=`${b.name} · Chapter ${p.chapter}`;document.getElementById('dashReadingMeta').textContent=`Resume at verse ${p.verse} · ${document.getElementById('readerTranslation')?.selectedOptions[0]?.textContent||'saved position'}`;document.getElementById('dashReadingNumber').textContent=`${p.chapter} / ${b.chapters}`;document.getElementById('addNextId').textContent=nextId(b);setSide();}
function populateChapters(){const b=currentBook(),p=readingPosition(b);populateChapterSelect('readerChapter',b.name,p.chapter)}
function syncReader(){const b=byName[document.getElementById('readerBook').value]||books[0];const old=readingPosition(b);setReadingPosition(b,Number(document.getElementById('readerChapter').value)||old.chapter,old.verse);renderReaderMeta();loadChapter()}
function renderReaderMeta(){const b=currentBook(),p=readingPosition(b);document.getElementById('readerBookLabel').textContent=b.name;document.getElementById('readerBookKicker').textContent=b.name.toUpperCase();document.getElementById('readerChapterLabel').textContent=p.chapter;document.getElementById('readerHeading').textContent=p.chapter;document.getElementById('addBook').value=b.name;populateChapterSelect('addChapter',b.name,p.chapter);updateBookProgressUI();if(document.querySelectorAll('#verseList p[data-verse]').length)updateReaderProgress(document.querySelectorAll('#verseList p[data-verse]').length)}
function changeChapter(delta){const b=currentBook(),p=readingPosition(b),next=Math.max(1,Math.min(b.chapters,p.chapter+delta));if(next===p.chapter)return;setReadingPosition(b,next,1);document.getElementById('readerChapter').value=next;renderReaderMeta();loadChapter();document.getElementById('verseList')?.scrollIntoView({behavior:'smooth'})}
function continueReading(){const l=state.reading.last||{book:'Pydāish',chapter:1,verse:1};const b=byName[l.book]||books[0];setReadingPosition(b,l.chapter,l.verse);document.getElementById('readerBook').value=b.name;populateChapters();renderReaderMeta();show('bible');loadChapter();setTimeout(()=>setVerse(l.verse,false),250)}
function setVerse(v,scroll=true){const b=currentBook(),p=readingPosition(b);setReadingPosition(b,p.chapter,v);document.querySelectorAll('#verseList p.reading-focus').forEach(x=>x.classList.remove('reading-focus'));const el=document.querySelector(`#verseList p[data-verse="${v}"]`);if(el){el.classList.add('reading-focus');if(scroll)el.scrollIntoView({behavior:'smooth',block:'center'})}updateReaderProgress(document.querySelectorAll('#verseList p[data-verse]').length);renderDashboardReading()}
function renderDashboardReading(){const b=currentBook(),p=readingPosition(b);updateBookProgressUI()}
function updateReaderProgress(total){const b=currentBook(),p=readingPosition(b),v=Math.max(1,Math.min(total||p.verse,p.verse));document.getElementById('readerProgressText').textContent=`Verse ${v} of ${total||'—'}`;document.getElementById('readerProgressBar').style.width=((v/(total||1))*100)+'%';updateBookProgressUI();renderReadingMap();}
function observeVerses(){if(window._io)window._io.disconnect();window._io=new IntersectionObserver(es=>{const visible=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible){const v=Number(visible.target.dataset.verse);if(v!==readingPosition(currentBook()).verse){setVerse(v,false)}}},{rootMargin:'-35% 0px -45% 0px',threshold:[.2,.6]});document.querySelectorAll('#verseList p[data-verse]').forEach(p=>window._io.observe(p))}
function renderChapter(d){const b=currentBook(),p=readingPosition(b),verses=(d?.verses||[]).filter(v=>v&&Number(v.number)>0&&v.text),bible=selectedBible()||{},direction=bibleLanguage(bible)==='ur'?'RTL':'LTR';const verseList=document.getElementById('verseList');verseList.dir=direction==='RTL'?'rtl':'ltr';verseList.lang=direction==='RTL'?'ur':'en';verseList.classList.toggle('rtl-reader',direction==='RTL');document.getElementById('readerHeading').textContent=p.chapter;document.getElementById('readerBookLabel').textContent=b.name;document.getElementById('readerBookKicker').textContent=b.name.toUpperCase();document.getElementById('readerChapterLabel').textContent=p.chapter;if(p.verse>verses.length){state.reading.positions[b.name].verse=verses.length||1;state.reading.verse=verses.length||1;save()}const active=readingPosition(b).verse;document.getElementById('readerProgressText').textContent=`Verse ${active} of ${verses.length}`;document.getElementById('readerProgressBar').style.width=((active/(verses.length||1))*100)+'%';verseList.innerHTML=verses.map(v=>`<p data-verse="${v.number}" tabindex="0" class="${Number(v.number)===active?'reading-focus':''}"><sup class="verse-no">${v.number}</sup> ${esc(v.text)}</p>`).join('');verseList.querySelectorAll('p[data-verse]').forEach(el=>{el.onclick=()=>setVerse(Number(el.dataset.verse));el.oncontextmenu=e=>{e.preventDefault();openReferenceDialog({from:{book:b.name,chapter:p.chapter,verse:Number(el.dataset.verse)}})}});observeVerses();updateReaderProgress(verses.length);updateNav();save()}
function updateNav(){const b=currentBook(),p=readingPosition(b),label=document.getElementById('nextChapterLabel');if(!label)return;const nextBook=books[b.index+1];label.textContent=p.chapter<b.chapters?`Chapter ${p.chapter+1}`:nextBook?`${nextBook.name} · Chapter 1`:'Finish Bible'}
function nextReaderStep(){const b=currentBook(),p=readingPosition(b);state.reading.completed[b.name+'|'+p.chapter]=new Date().toISOString();save();const nextChapter=p.chapter<b.chapters?p.chapter+1:null;const nextBook=books[b.index+1];if(nextChapter){setReadingPosition(b,nextChapter,1);document.getElementById('readerChapter').value=String(nextChapter);renderReaderMeta();loadChapter();document.getElementById('verseList')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(nextBook){setReadingPosition(nextBook,1,1);document.getElementById('readerBook').value=nextBook.name;populateChapters();renderReaderMeta();loadChapter();document.getElementById('verseList')?.scrollIntoView({behavior:'smooth',block:'start'});return}renderReaderMeta();renderReadingMap()}
async function midvashFetch(path){const r=await fetch(ENGLISH_API+path,{headers:{Accept:'application/json'}});if(!r.ok){let d='';try{const j=await r.json();d=j?.error?.message||j?.message||''}catch(_){}throw Error(`English Bible API ${r.status}${d?': '+d:''}`)}return r.json()}
function bibleLanguage(t){const raw=t?.language_tag??t?.language?.iso_639_1??t?.language?.id??t?.language??'';return String(raw).toLowerCase().split('-')[0]}
function isEnglishBible(t){return bibleLanguage(t)==='en'}
function bibleLabel(t){const title=t?.localized_title||t?.title||t?.name||t?.abbreviation||'Bible';const abbr=t?.localized_abbreviation||t?.shortName||t?.abbreviation||'';return abbr&&!String(title).toLowerCase().includes(String(abbr).toLowerCase())?`${title} — ${abbr}`:title}
const LOCAL_WORDPROJECT_URDU={id:'WP-URD',language_tag:'ur',language:{id:'ur',name:'Urdu',nameLocal:'اردو',scriptDirection:'RTL'},title:'Urdu Bible',localized_title:'WordProject Urdu Bible',abbreviation:'URD',localized_abbreviation:'URD',publisher:'WordProject',source:'WordProject',customUrdu:true};
const MIDVASH_BOOK_SLUGS={GEN:'genesis',EXO:'exodus',LEV:'leviticus',NUM:'numbers',DEU:'deuteronomy',JOS:'joshua',JDG:'judges',RUT:'ruth','1SA':'1-samuel','2SA':'2-samuel','1KI':'1-kings','2KI':'2-kings','1CH':'1-chronicles','2CH':'2-chronicles',EZR:'ezra',NEH:'nehemiah',EST:'esther',JOB:'job',PSA:'psalms',PRO:'proverbs',ECC:'ecclesiastes',SNG:'song-of-solomon',ISA:'isaiah',JER:'jeremiah',LAM:'lamentations',EZK:'ezekiel',DAN:'daniel',HOS:'hosea',JOL:'joel',AMO:'amos',OBA:'obadiah',JON:'jonah',MIC:'micah',NAM:'nahum',HAB:'habakkuk',ZEP:'zephaniah',HAG:'haggai',ZEC:'zechariah',MAL:'malachi',MAT:'matthew',MRK:'mark',LUK:'luke',JHN:'john',ACT:'acts',ROM:'romans','1CO':'1-corinthians','2CO':'2-corinthians',GAL:'galatians',EPH:'ephesians',PHP:'philippians',COL:'colossians','1TH':'1-thessalonians','2TH':'2-thessalonians','1TI':'1-timothy','2TI':'2-timothy',TIT:'titus',PHM:'philemon',HEB:'hebrews',JAS:'james','1PE':'1-peter','2PE':'2-peter','1JN':'1-john','2JN':'2-john','3JN':'3-john',JUD:'jude',REV:'revelation'};
const MIDVASH_FALLBACK_ENGLISH=[{id:'MV-kjv',language_tag:'en',title:'King James Version',localized_title:'King James Version',abbreviation:'KJV',shortName:'KJV',language:'en',source:'Midvash',midvash:true,versionSlug:'kjv'},{id:'MV-web',language_tag:'en',title:'World English Bible',localized_title:'World English Bible',abbreviation:'WEB',shortName:'WEB',language:'en',source:'Midvash',midvash:true,versionSlug:'web'},{id:'MV-asv',language_tag:'en',title:'American Standard Version',localized_title:'American Standard Version',abbreviation:'ASV',shortName:'ASV',language:'en',source:'Midvash',midvash:true,versionSlug:'asv'}];
let urduCatalog=null;
async function loadUrduCatalog(){try{const r=await fetch(`${URDU_BASE}/books.json`,{cache:'no-store'});if(!r.ok)throw Error();urduCatalog=await r.json();state.urduCatalog=urduCatalog;save();return urduCatalog}catch(e){urduCatalog=state.urduCatalog||null;return urduCatalog}}
function urduCodeForBook(book){const order=books.indexOf(book)+1;return urduCatalog?.books?.find(x=>Number(x.order)===order)?.code||book.code}
function isWordProjectUrdu(t){return String(t?.id)==='WP-URD'||t?.local===true}
function normalizeMidvashVersion(v){return {id:`MV-${v.slug}`,language_tag:'en',title:v.name||v.shortName||v.slug,localized_title:v.name||v.shortName||v.slug,abbreviation:v.shortName||v.slug.toUpperCase(),shortName:v.shortName||v.slug.toUpperCase(),language:v.language||'en',source:'Midvash',midvash:true,versionSlug:v.slug,copyright:v.copyright||''}}
async function loadEnglishCollection(){try{const d=await midvashFetch('/versions?language=en');const rows=Array.isArray(d?.data)?d.data:[];const versions=rows.filter(v=>String(v?.language||'').toLowerCase().startsWith('en')).map(normalizeMidvashVersion);if(versions.length)return versions}catch(e){}return MIDVASH_FALLBACK_ENGLISH}
async function loadTranslations(){await loadUrduCatalog();state.translations=[LOCAL_WORDPROJECT_URDU,...MIDVASH_FALLBACK_ENGLISH];if(state.selectedLanguage!=='en')state.selectedLanguage='ur';if(state.selectedLanguage==='ur')state.selectedTranslation='WP-URD';fillLanguages();const english=await loadEnglishCollection();state.translations=[LOCAL_WORDPROJECT_URDU,...english];state.englishSource='Midvash';save();fillLanguages()}
function fillLanguages(){const ls=document.getElementById('readerLanguage');const hasU=state.translations.some(isWordProjectUrdu),hasE=state.translations.some(isEnglishBible);ls.innerHTML=`${hasU?'<option value="ur">اردو</option>':''}${hasE?'<option value="en">English</option>':''}`;if(!((state.selectedLanguage==='ur'&&hasU)||(state.selectedLanguage==='en'&&hasE)))state.selectedLanguage=hasU?'ur':'en';ls.value=state.selectedLanguage;fillTranslations()}
function fillTranslations(){const lang=document.getElementById('readerLanguage').value;state.selectedLanguage=lang;const ts=document.getElementById('readerTranslation');const list=lang==='ur'?state.translations.filter(isWordProjectUrdu):state.translations.filter(isEnglishBible);ts.innerHTML=list.map(t=>`<option value="${esc(t.id)}">${esc(bibleLabel(t))}</option>`).join('');let pref=state.selectedTranslation;if(!list.some(t=>String(t.id)===String(pref)))pref=lang==='ur'?'WP-URD':list.find(t=>/king james/i.test(t.title||''))?.id||list[0]?.id;state.selectedTranslation=pref;ts.value=pref;save();loadChapter()}
function selectedBible(){return state.translations.find(t=>String(t.id)===String(document.getElementById('readerTranslation')?.value||state.selectedTranslation))||null}
async function loadChapter(){const list=document.getElementById('verseList');if(!list)return;list.innerHTML='<div class="loading-reader">Loading chapter…</div>';const b=currentBook(),p=readingPosition(b),bible=selectedBible();if(!bible)return;const key=`v15|${bible.customUrdu?'wordproject':'midvash'}|${bible.id}|${b.apiId}|${p.chapter}`;let d=state.cache[key];try{if(!d){if(bible.customUrdu){const r=await fetch(`${URDU_BASE}/${encodeURIComponent(urduCodeForBook(b))}/${p.chapter}.json`);if(!r.ok)throw Error(`Urdu Bible ${r.status}`);const j=await r.json();d={verses:(j?.verses||[]).map(v=>({number:Number(v.verse??v.number),text:String(v.text||'').trim()})).filter(v=>v.text)};if(!d.verses.length)throw Error('No Urdu verses were found.')}else{const slug=MIDVASH_BOOK_SLUGS[b.apiId];const j=await midvashFetch(`/${encodeURIComponent(bible.versionSlug)}/${slug}/${p.chapter}`);const payload=j?.data||j;d={verses:(payload?.verses||[]).map((v,i)=>typeof v==='string'?{number:i+1,text:v.trim()}:{number:Number(v?.verse??v?.number??i+1),text:String(v?.text||'').trim()}).filter(v=>v.text),copyright:j?.meta?.copyright||payload?.copyright||''};if(!d.verses.length)throw Error('The English Bible API returned no verses.')}state.cache[key]=d;save()}renderChapter(d)}catch(e){list.innerHTML=`<div class="empty large"><b>Could not load this chapter.</b><span>${esc(e.message)}<br>Previously opened chapters remain available offline.</span></div>`;toast('Bible chapter could not be loaded.')}}
function renderDashboard(){const qs=state.questions;const nums=[qs.length,qs.filter(q=>q.status==='Unanswered').length,qs.filter(q=>q.status==='Investigating'||q.status==='Need further investigation').length,qs.filter(q=>q.status==='Answered').length];document.querySelectorAll('.stats b').forEach((x,i)=>x.textContent=nums[i]||0);renderQuestionsByBook();renderReadingMap();updateBookProgressUI()}
function renderQuestionsByBook(){const host=document.getElementById('questionsByBook');const rows=books.map(b=>({b,n:state.questions.filter(q=>q.code===b.code).length})).filter(x=>x.n);host.innerHTML=rows.length?rows.map(x=>`<button class="book-question-row" data-book="${esc(x.b.name)}"><span>${esc(x.b.name)}</span><b>${x.n}</b></button>`).join(''):'<div class="empty compact"><i>◎</i><b>No questions yet</b><span>Add your first question to start the map.</span></div>';host.querySelectorAll('[data-book]').forEach(x=>x.onclick=()=>{show('questions');document.getElementById('questionBookFilter').value=x.dataset.book;renderQuestions()})}
function renderReadingMap(){const host=document.getElementById('readingMap');if(!host)return;const active=currentBook();host.innerHTML=books.map(b=>{const p=readingPosition(b),done=completedCount(b),current=b.name===active.name;const pct=done===b.chapters?100:Math.round(done/b.chapters*100);if(current)return `<button class="reading-current" data-book="${esc(b.name)}" title="${esc(b.name)}"><span>${esc(b.name)}</span><em>Chapter ${p.chapter}</em><i><b style="width:${Math.min(100,Math.round(p.chapter/b.chapters*100))}%"></b></i></button>`;return `<button class="reading-blob ${pct===100?'completed':''}" data-book="${esc(b.name)}" data-book-name="${esc(b.name)}" title="${esc(b.name)}"><span>${esc(b.code)}</span><em>${esc(b.name)}</em></button>`}).join('');host.querySelectorAll('[data-book]').forEach(el=>el.onclick=()=>jumpToBook(el.dataset.book));document.getElementById('overallReadingProgress').textContent=`${completedBooks()} / 66 completed`}
function jumpToBook(name){const b=byName[name],p=readingPosition(b);setReadingPosition(b,p.chapter,p.verse);document.getElementById('readerBook').value=b.name;populateChapters();renderReaderMeta();show('bible');loadChapter()}
function activeFilters(){const book=document.getElementById('questionBookFilter').value,cat=document.getElementById('questionCategoryFilter').value,status=document.getElementById('questionStatusFilter').value,search=document.getElementById('questionSearch').value.trim();const chips=[];if(book!=='All books')chips.push(['Book',book,'questionBookFilter']);if(cat!=='All categories')chips.push(['Category',cat,'questionCategoryFilter']);if(status!=='All statuses')chips.push(['Status',status,'questionStatusFilter']);if(search)chips.push(['Search',search,'questionSearch']);document.getElementById('activeFilters').innerHTML=chips.map(([l,v,id])=>`<button class="filter-chip" data-filter="${id}">${esc(l)}: ${esc(v)} ×</button>`).join('');document.querySelectorAll('.filter-chip').forEach(x=>x.onclick=()=>{const el=document.getElementById(x.dataset.filter);el.value='';if(el.tagName==='INPUT')el.value='';renderQuestions()})}
function renderQuestions(){const qb=document.getElementById('questionBookFilter'),qc=document.getElementById('questionCategoryFilter'),qs=document.getElementById('questionStatusFilter');if(!qb.options.length)qb.innerHTML='<option>All books</option>'+books.map(b=>`<option>${esc(b.name)}</option>`).join('');if(!qc.options.length)qc.innerHTML='<option>All categories</option>'+CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('');if(!qs.options.length)qs.innerHTML='<option>All statuses</option>'+STATUSES.map(s=>`<option>${esc(s)}</option>`).join('');const search=document.getElementById('questionSearch').value.toLowerCase(),book=qb.value,cat=qc.value,status=qs.value;const rows=state.questions.filter(q=>(!search||[q.id,q.book,q.question,formatRange(q.primaryReference),...(q.additionalReferences||[]).map(formatRange)].join(' ').toLowerCase().includes(search))&&(book==='All books'||q.book===book)&&(cat==='All categories'||q.category===cat)&&(status==='All statuses'||q.status===status));activeFilters();const body=document.querySelector('#questions tbody');if(!rows.length){body.innerHTML='<tr><td colspan="5" class="empty">☷<br><b>No matching questions</b><br><span>Change the filters or save another question.</span></td></tr>';return}body.innerHTML=rows.map(q=>`<tr draggable="true" data-uid="${esc(q.uid)}"><td><b>${esc(q.id)}</b></td><td>${esc(formatRange(q.primaryReference))}${q.additionalReferences?.length?` <span class="additional-ref">+${q.additionalReferences.length} additional</span>`:''}</td><td><div class="question-cell"><span>${esc(q.question)}</span><div class="row-actions"><button data-action="edit">Edit</button><button data-action="research">Research</button><button data-action="delete">Delete</button></div></div></td><td>${esc(q.category)}</td><td><span class="status-pill">${esc(q.status)}</span></td></tr>`).join('');bindQuestionRows(body);}
function bindQuestionRows(body){let dragUid=null;body.querySelectorAll('tr[data-uid]').forEach(row=>{row.addEventListener('dragstart',e=>{dragUid=row.dataset.uid;row.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragUid)});row.addEventListener('dragend',()=>row.classList.remove('dragging'));row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('drag-over')});row.addEventListener('dragleave',()=>row.classList.remove('drag-over'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('drag-over');reorderQuestion(dragUid,row.dataset.uid)});row.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action){e.stopPropagation();const q=state.questions.find(x=>x.uid===row.dataset.uid);if(action.dataset.action==='edit')openEdit(q.uid);if(action.dataset.action==='research')openResearch(q.uid);if(action.dataset.action==='delete')deleteQuestion(q.uid);return}if(window.matchMedia('(max-width:760px)').matches)row.classList.toggle('actions-open')})})}
function reorderQuestion(uidA,uidB){const a=state.questions.findIndex(q=>q.uid===uidA),b=state.questions.findIndex(q=>q.uid===uidB);if(a<0||b<0)return;const qa=state.questions[a],qb=state.questions[b];if(qa.code!==qb.code){toast('Questions can only be reordered within the same book.');return}const [moved]=state.questions.splice(a,1);let target=state.questions.findIndex(q=>q.uid===uidB);state.questions.splice(target,0,moved);renumberBook(qa.code);renderQuestions();toast('Question order updated.')}
function deleteQuestion(uidToDelete){const q=state.questions.find(x=>x.uid===uidToDelete);if(!q)return;if(!confirm(`Delete ${q.id}? This will renumber later questions in ${q.book}.`))return;state.questions=state.questions.filter(x=>x.uid!==uidToDelete);renumberBook(q.code);if(window.selectedQuestionUid===uidToDelete)window.selectedQuestionUid=null;save();cloudDeleteQuestion(uidToDelete);renderQuestions();renderDashboard();renderResearch();toast('Question deleted and IDs reordered.')}
function referenceEditorHTML(prefix,data={from:{book:currentBook().name,chapter:readingPosition(currentBook()).chapter,verse:readingPosition(currentBook()).verse},to:null},allowEmpty=false){const from=data.from||data;const to=data.to||from;return `<div class="reference-editor" data-ref-editor="${prefix}"><div class="ref-title"><strong>${prefix==='primary'?'Primary reference':'Additional reference'}</strong>${allowEmpty?'<button type="button" class="remove-ref">Remove</button>':''}</div><div class="ref-grid"><label>Book<select class="ref-from-book">${books.map(b=>`<option value="${esc(b.name)}" ${b.name===from.book?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label><label class="check-line"><input type="checkbox" class="ref-book-range" ${data.to&&data.to.book!==from.book?'checked':''}> Range</label><label>End book<select class="ref-to-book" ${!(data.to&&data.to.book!==from.book)?'disabled':''}>${books.map(b=>`<option value="${esc(b.name)}" ${b.name===to.book?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label><label>Chapter<select class="ref-from-chapter"></select></label><label class="check-line"><input type="checkbox" class="ref-chapter-range" ${data.to&&data.to.chapter!==from.chapter?'checked':''}> Range</label><label>End chapter<select class="ref-to-chapter" ${!(data.to&&data.to.chapter!==from.chapter)?'disabled':''}></select></label><label>Verse<input class="ref-from-verse" type="number" min="1" value="${Number(from.verse)||1}"></label><label>End verse<input class="ref-to-verse" type="number" min="1" value="${Number(to.verse)||Number(from.verse)||1}" ${data.to?'':'disabled'}></label></div></div>`}
function wireReferenceEditor(root){const fb=root.querySelector('.ref-from-book'),tb=root.querySelector('.ref-to-book'),fc=root.querySelector('.ref-from-chapter'),tc=root.querySelector('.ref-to-chapter'),br=root.querySelector('.ref-book-range'),cr=root.querySelector('.ref-chapter-range'),ev=root.querySelector('.ref-to-verse');function refresh(){const b=byName[fb.value]||books[0],oldF=Number(fc.value)||1,oldT=Number(tc.value)||oldF;populateChapterSelectNode(fc,b,oldF);const endBook=byName[tb.value]||b;populateChapterSelectNode(tc,endBook,oldT);tb.disabled=!br.checked;tc.disabled=!(br.checked||cr.checked);ev.disabled=!(cr.checked||br.checked||Number(ev.value)!==Number(root.querySelector('.ref-from-verse').value));if(!br.checked)tb.value=b.name;if(!cr.checked&&!br.checked)tc.value=fc.value}function populateChapterSelectNode(sel,b,selected){sel.innerHTML=Array.from({length:b.chapters},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');sel.value=String(Math.min(Math.max(1,Number(selected)||1),b.chapters))}fb.onchange=refresh;tb.onchange=refresh;br.onchange=()=>{if(br.checked){tb.disabled=false;cr.checked=true;tc.disabled=false}else{tb.disabled=true;tb.value=fb.value;if(!cr.checked)tc.disabled=true}refresh()};cr.onchange=()=>{tc.disabled=!(cr.checked||br.checked);ev.disabled=!(cr.checked||br.checked);if(!cr.checked&&!br.checked)tc.value=fc.value};fc.onchange=()=>{if(!cr.checked&&!br.checked)tc.value=fc.value};refresh();if(root.querySelector('.remove-ref'))root.querySelector('.remove-ref').onclick=()=>root.remove()}
function getReferenceFromEditor(root){const fb=root.querySelector('.ref-from-book').value,tb=root.querySelector('.ref-to-book').value,fc=Number(root.querySelector('.ref-from-chapter').value)||1,tc=Number(root.querySelector('.ref-to-chapter').value)||fc,fv=Number(root.querySelector('.ref-from-verse').value)||1,tv=Number(root.querySelector('.ref-to-verse').value)||fv;const toNeeded=root.querySelector('.ref-book-range').checked||root.querySelector('.ref-chapter-range').checked||tv!==fv;return normalizeRange({from:{book:fb,chapter:fc,verse:fv},to:toNeeded?{book:tb,chapter:tc,verse:tv}:null},byName[fb])}
function openReferenceDialog(prefill){const container=document.getElementById('referenceSections');container.innerHTML=referenceEditorHTML('primary',prefill||{from:{book:currentBook().name,chapter:readingPosition(currentBook()).chapter,verse:readingPosition(currentBook()).verse},to:null})+`<div id="additionalRefs"></div><button type="button" class="outline add-ref-btn" id="addAdditionalRef">＋ Add additional reference</button>`;wireReferenceEditor(container.querySelector('[data-ref-editor]'));document.getElementById('addAdditionalRef').onclick=()=>{const host=document.getElementById('additionalRefs');const wrap=document.createElement('div');wrap.innerHTML=referenceEditorHTML('additional',{from:{book:currentBook().name,chapter:readingPosition(currentBook()).chapter,verse:readingPosition(currentBook()).verse},to:null},true);host.appendChild(wrap.firstElementChild);wireReferenceEditor(host.lastElementChild)};const dlg=document.getElementById('referenceDialog');dlg.showModal()}
document.getElementById('referenceForm').addEventListener('submit',e=>{if(e.submitter?.id!=='referenceSave')return;e.preventDefault();const editors=[...document.querySelectorAll('#referenceSections [data-ref-editor]')];const primary=getReferenceFromEditor(editors[0]);const adds=editors.slice(1).map(getReferenceFromEditor);openAddFromReference(primary,adds);document.getElementById('referenceDialog').close()});
function openAddFromReference(primary,adds=[]){show('add');const b=byName[primary.from.book]||currentBook();document.getElementById('addBook').value=b.name;populateChapterSelect('addChapter',b.name,primary.from.chapter);document.getElementById('addReference').value=formatRange(primary);document.getElementById('addAdditional').value=adds.map(formatRange).join('; ');document.getElementById('addNextId').textContent=nextId(b);}
function openAdd(ref){if(ref){const p=parseLegacyReference(ref,currentBook());openAddFromReference(p||{from:{book:currentBook().name,chapter:readingPosition(currentBook()).chapter,verse:readingPosition(currentBook()).verse},to:null})}else show('add')}
function clearAdd(){document.getElementById('addReference').value='';document.getElementById('addAdditional').value='';document.getElementById('addQuestionText').value='';document.getElementById('addWhy').value='';document.getElementById('addRelated').value=''}
function getAddForm(){return {book:document.getElementById('addBook').value,chapter:Number(document.getElementById('addChapter').value)||1,ref:document.getElementById('addReference').value.trim(),additional:document.getElementById('addAdditional').value.trim(),question:document.getElementById('addQuestionText').value.trim(),why:document.getElementById('addWhy').value.trim(),category:document.getElementById('addCategory').value,related:document.getElementById('addRelated').value.trim()}}
function saveQuestion(){const f=getAddForm();if(!f.question){toast('Write your question first.');return}const b=byName[f.book]||currentBook();const primary=parseLegacyReference(f.ref,b)||{from:{book:b.name,chapter:f.chapter,verse:1},to:null};const additional=f.additional.split(';').map(x=>parseLegacyReference(x,b)).filter(Boolean);const q={uid:uid(),id:nextId(b),code:b.code,book:b.name,chapter:primary.from.chapter,primaryReference:primary,additionalReferences:additional,references:[formatRange(primary),...additional.map(formatRange)],question:f.question,why:f.why,category:f.category,status:'Unanswered',related:f.related.split(',').map(x=>x.trim()).filter(Boolean),investigation:'',sources:'',conclusion:'',createdAt:new Date().toISOString(),researchUi:{x:null,y:null,minimized:false}};state.questions.push(q);save();clearAdd();document.getElementById('addNextId').textContent=nextId(b);toast(`${q.id} saved.`);renderDashboard();renderQuestions()}
function editFieldsHTML(q){return `<div class="edit-grid"><label>Book<select id="editBook">${books.map(b=>`<option ${b.name===q.book?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label><label>Category<select id="editCategory">${CATEGORIES.map(c=>`<option ${c===q.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Primary reference<input id="editReference" value="${esc(formatRange(q.primaryReference))}"></label><label>Additional references<input id="editAdditional" value="${esc((q.additionalReferences||[]).map(formatRange).join('; '))}"></label><label>Status<select id="editStatus">${STATUSES.map(s=>`<option ${s===q.status?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Related question IDs<input id="editRelated" value="${esc((q.related||[]).join(', '))}"></label><label class="full-field">Question<textarea id="editQuestion" class="big">${esc(q.question)}</textarea></label><label class="full-field">Why did I ask this?<textarea id="editWhy">${esc(q.why)}</textarea></label><label class="full-field">Investigation / Answer<textarea id="editInvestigation">${esc(q.investigation)}</textarea></label><label class="full-field">Sources / Cross-references<textarea id="editSources">${esc(q.sources)}</textarea></label><label class="full-field">Conclusion / Current Understanding<textarea id="editConclusion">${esc(q.conclusion)}</textarea></label></div>`}
function openEdit(uidToEdit){const q=state.questions.find(x=>x.uid===uidToEdit);if(!q)return;document.getElementById('editFields').innerHTML=editFieldsHTML(q);const dlg=document.getElementById('editDialog');dlg.showModal();document.getElementById('editSave').onclick=e=>{e.preventDefault();const oldCode=q.code,newBook=byName[document.getElementById('editBook').value];q.book=newBook.name;q.code=newBook.code;q.primaryReference=parseLegacyReference(document.getElementById('editReference').value,newBook)||q.primaryReference;q.additionalReferences=document.getElementById('editAdditional').value.split(';').map(x=>parseLegacyReference(x,newBook)).filter(Boolean);q.references=[formatRange(q.primaryReference),...q.additionalReferences.map(formatRange)];q.chapter=q.primaryReference.from.chapter;q.category=document.getElementById('editCategory').value;q.status=document.getElementById('editStatus').value;q.question=document.getElementById('editQuestion').value.trim();q.why=document.getElementById('editWhy').value.trim();q.related=document.getElementById('editRelated').value.split(',').map(x=>x.trim()).filter(Boolean);q.investigation=document.getElementById('editInvestigation').value;q.sources=document.getElementById('editSources').value;q.conclusion=document.getElementById('editConclusion').value;if(oldCode!==q.code){renumberBook(oldCode);renumberBook(q.code)}else renumberBook(q.code);save();dlg.close();renderQuestions();renderDashboard();if(window.selectedQuestionUid===q.uid)renderResearch();toast('Question updated.')}}
function openResearch(uidToOpen){window.selectedQuestionUid=uidToOpen;show('research')}
function renderResearch(){const p=document.getElementById('researchPanel'),q=state.questions.find(x=>x.uid===window.selectedQuestionUid);if(!q){p.className='panel research-empty';p.innerHTML=`<div class="empty large">⌕<h3>Select a question to research</h3><span>Choose a question directly here, or use the Research action in the library.</span><label class="research-picker">Question<select id="researchQuestionPicker"><option value="">Select a question…</option>${state.questions.map(x=>`<option value="${x.uid}">${esc(x.id)} · ${esc(x.question.slice(0,80))}</option>`).join('')}</select></label></div>`;document.getElementById('researchQuestionPicker').onchange=e=>{if(e.target.value)openResearch(e.target.value)};return}p.className='panel research-panel';p.innerHTML=`<div class="research-head"><div><small>${esc(q.id)} · ${esc(q.book)} · ${esc(formatRange(q.primaryReference))}</small><h3>${esc(q.question)}</h3><p>${esc(q.why||'No reason recorded.')}</p></div><button class="close-question" id="closeResearchQuestion" type="button" title="Close question">×</button></div><div class="research-actions"><label>Status<select id="researchStatus">${STATUSES.map(s=>`<option ${s===q.status?'selected':''}>${esc(s)}</option>`).join('')}</select></label><button class="primary" id="onlineResearchBtn" type="button">Search online</button></div><div class="research-grid"><label>Investigation / Answer<textarea id="researchInvestigation" class="big">${esc(q.investigation)}</textarea></label><label>Sources / Cross-references<textarea id="researchSources" placeholder="Books, articles, passages, links…">${esc(q.sources)}</textarea></label><label class="full-field">Conclusion / Current Understanding<textarea id="researchConclusion">${esc(q.conclusion)}</textarea></label></div><div class="actions"><button class="primary" id="saveResearchButton" type="button">Save Research</button></div>`;document.getElementById('closeResearchQuestion').onclick=()=>{window.selectedQuestionUid=null;renderResearch()};document.getElementById('researchStatus').onchange=e=>{q.status=e.target.value;save();renderQuestions();renderDashboard()};document.getElementById('saveResearchButton').onclick=saveResearch;document.getElementById('onlineResearchBtn').onclick=()=>openOnlineResearch(q.uid)}
function saveResearch(){const q=state.questions.find(x=>x.uid===window.selectedQuestionUid);if(!q)return;q.investigation=document.getElementById('researchInvestigation').value;q.sources=document.getElementById('researchSources').value;q.conclusion=document.getElementById('researchConclusion').value;save();toast('Research saved.');renderQuestions();renderDashboard()}
function buildResearchQuery(q){const refs=[formatRange(q.primaryReference),...(q.additionalReferences||[]).map(formatRange)].filter(Boolean).join('; ');return `${q.question}${refs?` | References: ${refs}`:''}${q.category?` | Category: ${q.category}`:''} | Bible question research`}
function saveBubblePosition(){const b=document.getElementById('researchBubble');const q=state.questions.find(x=>x.uid===window.selectedQuestionUid);if(!q)return;const r=b.getBoundingClientRect();q.researchUi=q.researchUi||{};q.researchUi.x=Math.max(0,Math.round(r.left));q.researchUi.y=Math.max(0,Math.round(r.top));save()}
function restoreBubble(q){const b=document.getElementById('researchBubble');b.dataset.uid=q.uid;b.hidden=false;const x=q.researchUi?.x,y=q.researchUi?.y;b.style.left=`${Math.min(Math.max(8,x??window.innerWidth-72),window.innerWidth-64)}px`;b.style.top=`${Math.min(Math.max(8,y??window.innerHeight-72),window.innerHeight-64)}px`}
function runOnlineSearch(){const q=state.questions.find(x=>x.uid===window.selectedQuestionUid);if(!q)return;const query=buildResearchQuery(q).trim();if(!query)return;const url=`https://www.google.com/search?igu=1&q=${encodeURIComponent(query)}`;document.getElementById('researchSearchResults').innerHTML=`<iframe class="research-frame" data-research-uid="${esc(q.uid)}" title="Google Search" src="${esc(url)}"></iframe>`}
function openOnlineResearch(uidToOpen){window.selectedQuestionUid=uidToOpen;const q=state.questions.find(x=>x.uid===uidToOpen);if(!q)return;q.researchUi=q.researchUi||{x:null,y:null,minimized:false};q.researchUi.minimized=false;save();const bubble=document.getElementById('researchBubble');bubble.hidden=true;bubble.dataset.uid=q.uid;document.getElementById('researchSearchTitle').textContent=`Search online · ${q.id}`;const dialog=document.getElementById('researchSearchDialog');if(!dialog.open)dialog.showModal();const existing=document.querySelector('#researchSearchResults iframe.research-frame');if(!existing||existing.dataset.researchUid!==q.uid)runOnlineSearch()}
function minimizeOnlineResearch(){const b=document.getElementById('researchBubble');const uid=b.dataset.uid||window.selectedQuestionUid;const q=state.questions.find(x=>x.uid===uid);if(!q)return;window.selectedQuestionUid=q.uid;q.researchUi=q.researchUi||{x:null,y:null,minimized:false};q.researchUi.minimized=true;save();const dialog=document.getElementById('researchSearchDialog');if(dialog.open)dialog.close();restoreBubble(q)}
function restoreOnlineResearch(){const b=document.getElementById('researchBubble');const uid=b.dataset.uid||window.selectedQuestionUid;const q=state.questions.find(x=>x.uid===uid);if(!q)return;window.selectedQuestionUid=q.uid;q.researchUi=q.researchUi||{x:null,y:null,minimized:false};q.researchUi.minimized=false;save();b.hidden=true;document.getElementById('researchSearchTitle').textContent=`Search online · ${q.id}`;const dialog=document.getElementById('researchSearchDialog');try{if(!dialog.open)dialog.showModal()}catch(e){dialog.removeAttribute('open');dialog.showModal()}const existing=document.querySelector('#researchSearchResults iframe.research-frame');if(!existing||existing.dataset.researchUid!==q.uid)runOnlineSearch()}
document.getElementById('researchSearchMinimize').onclick=minimizeOnlineResearch;document.getElementById('closeSearchDialog').onclick=()=>{const q=state.questions.find(x=>x.uid===window.selectedQuestionUid);if(q){q.researchUi=q.researchUi||{};q.researchUi.minimized=false;save();}document.getElementById('researchSearchDialog').close();document.getElementById('researchBubble').hidden=true};
function makeDraggableBubble(){const bubble=document.getElementById('researchBubble');let drag=false,ox=0,oy=0,moved=false;bubble.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;drag=true;moved=false;ox=e.clientX-bubble.offsetLeft;oy=e.clientY-bubble.offsetTop;bubble.setPointerCapture?.(e.pointerId);e.preventDefault()});bubble.addEventListener('pointermove',e=>{if(!drag)return;if(Math.abs(e.clientX-(bubble.offsetLeft+ox))>4||Math.abs(e.clientY-(bubble.offsetTop+oy))>4)moved=true;bubble.style.left=`${Math.min(Math.max(8,e.clientX-ox),window.innerWidth-64)}px`;bubble.style.top=`${Math.min(Math.max(8,e.clientY-oy),window.innerHeight-64)}px`});bubble.addEventListener('pointerup',e=>{if(!drag)return;drag=false;saveBubblePosition();if(!moved)restoreOnlineResearch()});bubble.addEventListener('click',e=>{e.preventDefault();e.stopPropagation()})}
makeDraggableBubble();
function copyRef(){const b=currentBook(),p=readingPosition(b);const text=`${b.name} ${p.chapter}:${p.verse}`;navigator.clipboard?.writeText(text).then(()=>toast('Reference copied.')).catch(()=>toast(text))}
function searchChapter(){const term=prompt('Search this chapter:');if(!term)return;const p=[...document.querySelectorAll('#verseList p[data-verse]')].find(x=>x.textContent.toLowerCase().includes(term.toLowerCase()));if(p){setVerse(Number(p.dataset.verse));toast(`Found at verse ${p.dataset.verse}.`)}else toast('No match in this chapter.')}
function compare(){toast('Only one translation is currently loaded for Urdu. English comparison can be made from the translation menu.')}
function resetReadingForBook(book){const b=book||currentBook();if(!confirm(`Reset reading status and saved position for ${b.name}?`))return;Object.keys(state.reading.completed).forEach(k=>{if(k.startsWith(b.name+'|'))delete state.reading.completed[k]});state.reading.positions[b.name]={chapter:1,verse:1};setReadingPosition(b,1,1);renderReaderMeta();renderReadingMap();renderDashboard();loadChapter()}
function resetAllReading(){if(!confirm('Reset reading status and saved position for all 66 books?'))return;state.reading.completed={};state.reading.positions={};books.forEach(b=>{state.reading.positions[b.name]={chapter:1,verse:1}});state.reading.book='Pydāish';state.reading.chapter=1;state.reading.verse=1;state.reading.last={book:'Pydāish',chapter:1,verse:1};save();document.getElementById('readerBook').value='Pydāish';populateChapters();renderReaderMeta();renderReadingMap();renderDashboard();loadChapter()}
function initialize(){populateBookSelect('addBook',currentBook().name);populateChapterSelect('addChapter',currentBook().name,readingPosition(currentBook()).chapter);const cat=document.getElementById('addCategory');cat.innerHTML=CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('');document.getElementById('readerBook').innerHTML=books.map(b=>`<option value="${esc(b.name)}">${esc(b.name)}</option>`).join('');document.getElementById('readerBook').value=currentBook().name;populateChapters();document.getElementById('readerChapter').value=String(readingPosition(currentBook()).chapter);document.getElementById('readerBook').onchange=()=>{const b=byName[document.getElementById('readerBook').value]||books[0];const p=readingPosition(b);setReadingPosition(b,p.chapter,p.verse);populateChapters();renderReaderMeta();loadChapter()};document.getElementById('readerChapter').onchange=()=>{setReadingPosition(currentBook(),Number(document.getElementById('readerChapter').value),1);renderReaderMeta();loadChapter()};document.getElementById('readerLanguage').onchange=()=>{state.selectedLanguage=document.getElementById('readerLanguage').value;state.selectedTranslation=state.selectedLanguage==='ur'?'WP-URD':null;save();fillTranslations()};document.getElementById('readerTranslation').onchange=()=>{state.selectedTranslation=document.getElementById('readerTranslation').value;save();loadChapter()};document.querySelector('.reader-book-button').onclick=()=>document.getElementById('readerBook').focus();document.querySelector('.chapter-jump').onclick=()=>document.getElementById('readerChapter').focus();document.querySelector('[title="Search"]').onclick=searchChapter;document.querySelector('[title="Reader settings"]').onclick=()=>document.getElementById('readerLanguage').focus();document.getElementById('nextChapterButton').onclick=nextReaderStep;document.getElementById('resetCurrentReading').onclick=()=>resetReadingForBook(currentBook());document.getElementById('resetAllReading').onclick=resetAllReading;document.getElementById('studyAddQuestion').onclick=()=>openReferenceDialog({from:{book:currentBook().name,chapter:readingPosition(currentBook()).chapter,verse:readingPosition(currentBook()).verse},to:null});document.getElementById('continueReadingBtn').onclick=continueReading;document.querySelector('#addBook').onchange=()=>populateChapterSelect('addChapter',document.getElementById('addBook').value,1);document.getElementById('addSaveButton').onclick=saveQuestion;document.getElementById('questionSearch').oninput=renderQuestions;['questionBookFilter','questionCategoryFilter','questionStatusFilter'].forEach(id=>document.getElementById(id).onchange=renderQuestions);document.getElementById('researchPanel').addEventListener('input',()=>{});setSide();renderReaderMeta();renderDashboard();renderQuestions();renderResearch();loadTranslations()}
window.show=show;window.openAdd=openAdd;window.toast=toast;
bootAuth();
if('serviceWorker' in navigator){ navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}); }
